# Generated by Django 5.0 on 2023-12-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='seller',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
